### ISSUE TITLE
TypeError - when npm run start

### ISSUE THREAD

**Issue by lukewoolh** [ConsumerDataStandardsAustralia/banking-products-comparator#12]
On new install of NodeJS, getting following error when 'npm run start':

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\index.js:317:13)
    at C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\index.js:317:13)
    at C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\dev\banking-products-comparator-master\banking-products-comparator-master\node_modules\express\lib\router\layer.js:95:5)

Is there additional config required (not documented) to see web app in dev?

**Comment by lukewoolh** [comment]
Updating to react-scripts 3.4.0 fixed above issue.
